<?php

namespace Modules\Province\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;
use Modules\Province\Entities\City;

class CityDatabaseSeeder extends Seeder
{

    public function run()
    {
        City::truncate();

        $locations = array(
            array('id' => '1','name' => 'تبريز','province_id' => '1'),
            array('id' => '2','name' => 'كندوان','province_id' => '1'),
            array('id' => '3','name' => 'بندر شرفخانه','province_id' => '1'),
            array('id' => '4','name' => 'مراغه','province_id' => '1'),
            array('id' => '5','name' => 'ميانه','province_id' => '1'),
            array('id' => '6','name' => 'شبستر','province_id' => '1'),
            array('id' => '7','name' => 'مرند','province_id' => '1'),
            array('id' => '8','name' => 'جلفا','province_id' => '1'),
            array('id' => '9','name' => 'سراب','province_id' => '1'),
            array('id' => '10','name' => 'هاديشهر','province_id' => '1'),
            array('id' => '11','name' => 'بناب','province_id' => '1'),
            array('id' => '12','name' => 'كليبر','province_id' => '1'),
            array('id' => '13','name' => 'تسوج','province_id' => '1'),
            array('id' => '14','name' => 'اهر','province_id' => '1'),
            array('id' => '15','name' => 'هريس','province_id' => '1'),
            array('id' => '16','name' => 'عجبشير','province_id' => '1'),
            array('id' => '17','name' => 'هشترود','province_id' => '1'),
            array('id' => '18','name' => 'ملكان','province_id' => '1'),
            array('id' => '19','name' => 'بستان آباد','province_id' => '1'),
            array('id' => '20','name' => 'ورزقان','province_id' => '1'),
            array('id' => '21','name' => 'اسكو','province_id' => '1'),
            array('id' => '22','name' => 'آذر شهر','province_id' => '1'),
            array('id' => '23','name' => 'قره آغاج','province_id' => '1'),
            array('id' => '24','name' => 'ممقان','province_id' => '1'),
            array('id' => '25','name' => 'صوفیان','province_id' => '1'),
            array('id' => '26','name' => 'ایلخچی','province_id' => '1'),
            array('id' => '27','name' => 'خسروشهر','province_id' => '1'),
            array('id' => '28','name' => 'باسمنج','province_id' => '1'),
            array('id' => '29','name' => 'سهند','province_id' => '1'),
            array('id' => '30','name' => 'اروميه','province_id' => '2'),
            array('id' => '31','name' => 'نقده','province_id' => '2'),
            array('id' => '32','name' => 'ماكو','province_id' => '2'),
            array('id' => '33','name' => 'تكاب','province_id' => '2'),
            array('id' => '34','name' => 'خوي','province_id' => '2'),
            array('id' => '35','name' => 'مهاباد','province_id' => '2'),
            array('id' => '36','name' => 'سر دشت','province_id' => '2'),
            array('id' => '37','name' => 'چالدران','province_id' => '2'),
            array('id' => '38','name' => 'بوكان','province_id' => '2'),
            array('id' => '39','name' => 'مياندوآب','province_id' => '2'),
            array('id' => '40','name' => 'سلماس','province_id' => '2'),
            array('id' => '41','name' => 'شاهين دژ','province_id' => '2'),
            array('id' => '42','name' => 'پيرانشهر','province_id' => '2'),
            array('id' => '43','name' => 'سيه چشمه','province_id' => '2'),
            array('id' => '44','name' => 'اشنويه','province_id' => '2'),
            array('id' => '45','name' => 'چایپاره','province_id' => '2'),
            array('id' => '46','name' => 'پلدشت','province_id' => '2'),
            array('id' => '47','name' => 'شوط','province_id' => '2'),
            array('id' => '48','name' => 'اردبيل','province_id' => '3'),
            array('id' => '49','name' => 'سرعين','province_id' => '3'),
            array('id' => '50','name' => 'بيله سوار','province_id' => '3'),
            array('id' => '51','name' => 'پارس آباد','province_id' => '3'),
            array('id' => '52','name' => 'خلخال','province_id' => '3'),
            array('id' => '53','name' => 'مشگين شهر','province_id' => '3'),
            array('id' => '54','name' => 'مغان','province_id' => '3'),
            array('id' => '55','name' => 'نمين','province_id' => '3'),
            array('id' => '56','name' => 'نير','province_id' => '3'),
            array('id' => '57','name' => 'كوثر','province_id' => '3'),
            array('id' => '58','name' => 'كيوي','province_id' => '3'),
            array('id' => '59','name' => 'گرمي','province_id' => '3'),
            array('id' => '60','name' => 'اصفهان','province_id' => '4'),
            array('id' => '61','name' => 'فريدن','province_id' => '4'),
            array('id' => '62','name' => 'فريدون شهر','province_id' => '4'),
            array('id' => '63','name' => 'فلاورجان','province_id' => '4'),
            array('id' => '64','name' => 'گلپايگان','province_id' => '4'),
            array('id' => '65','name' => 'دهاقان','province_id' => '4'),
            array('id' => '66','name' => 'نطنز','province_id' => '4'),
            array('id' => '67','name' => 'نايين','province_id' => '4'),
            array('id' => '68','name' => 'تيران','province_id' => '4'),
            array('id' => '69','name' => 'كاشان','province_id' => '4'),
            array('id' => '70','name' => 'فولاد شهر','province_id' => '4'),
            array('id' => '71','name' => 'اردستان','province_id' => '4'),
            array('id' => '72','name' => 'سميرم','province_id' => '4'),
            array('id' => '73','name' => 'درچه','province_id' => '4'),
            array('id' => '74','name' => 'کوهپایه','province_id' => '4'),
            array('id' => '75','name' => 'مباركه','province_id' => '4'),
            array('id' => '76','name' => 'شهرضا','province_id' => '4'),
            array('id' => '77','name' => 'خميني شهر','province_id' => '4'),
            array('id' => '78','name' => 'شاهين شهر','province_id' => '4'),
            array('id' => '79','name' => 'نجف آباد','province_id' => '4'),
            array('id' => '80','name' => 'دولت آباد','province_id' => '4'),
            array('id' => '81','name' => 'زرين شهر','province_id' => '4'),
            array('id' => '82','name' => 'آران و بيدگل','province_id' => '4'),
            array('id' => '83','name' => 'باغ بهادران','province_id' => '4'),
            array('id' => '84','name' => 'خوانسار','province_id' => '4'),
            array('id' => '85','name' => 'مهردشت','province_id' => '4'),
            array('id' => '86','name' => 'علويجه','province_id' => '4'),
            array('id' => '87','name' => 'عسگران','province_id' => '4'),
            array('id' => '88','name' => 'نهضت آباد','province_id' => '4'),
            array('id' => '89','name' => 'حاجي آباد','province_id' => '4'),
            array('id' => '90','name' => 'تودشک','province_id' => '4'),
            array('id' => '91','name' => 'ورزنه','province_id' => '4'),
            array('id' => '92','name' => 'ايلام','province_id' => '6'),
            array('id' => '93','name' => 'مهران','province_id' => '6'),
            array('id' => '94','name' => 'دهلران','province_id' => '6'),
            array('id' => '95','name' => 'آبدانان','province_id' => '6'),
            array('id' => '96','name' => 'شيروان چرداول','province_id' => '6'),
            array('id' => '97','name' => 'دره شهر','province_id' => '6'),
            array('id' => '98','name' => 'ايوان','province_id' => '6'),
            array('id' => '99','name' => 'سرابله','province_id' => '6'),
            array('id' => '100','name' => 'بوشهر','province_id' => '7'),
            array('id' => '101','name' => 'تنگستان','province_id' => '7'),
            array('id' => '102','name' => 'دشتستان','province_id' => '7'),
            array('id' => '103','name' => 'دير','province_id' => '7'),
            array('id' => '104','name' => 'ديلم','province_id' => '7'),
            array('id' => '105','name' => 'كنگان','province_id' => '7'),
            array('id' => '106','name' => 'گناوه','province_id' => '7'),
            array('id' => '107','name' => 'ريشهر','province_id' => '7'),
            array('id' => '108','name' => 'دشتي','province_id' => '7'),
            array('id' => '109','name' => 'خورموج','province_id' => '7'),
            array('id' => '110','name' => 'اهرم','province_id' => '7'),
            array('id' => '111','name' => 'برازجان','province_id' => '7'),
            array('id' => '112','name' => 'خارك','province_id' => '7'),
            array('id' => '113','name' => 'جم','province_id' => '7'),
            array('id' => '114','name' => 'کاکی','province_id' => '7'),
            array('id' => '115','name' => 'عسلویه','province_id' => '7'),
            array('id' => '116','name' => 'بردخون','province_id' => '7'),
            array('id' => '117','name' => 'تهران','province_id' => '8'),
            array('id' => '118','name' => 'ورامين','province_id' => '8'),
            array('id' => '119','name' => 'فيروزكوه','province_id' => '8'),
            array('id' => '120','name' => 'ري','province_id' => '8'),
            array('id' => '121','name' => 'دماوند','province_id' => '8'),
            array('id' => '122','name' => 'اسلامشهر','province_id' => '8'),
            array('id' => '123','name' => 'رودهن','province_id' => '8'),
            array('id' => '124','name' => 'لواسان','province_id' => '8'),
            array('id' => '125','name' => 'بومهن','province_id' => '8'),
            array('id' => '126','name' => 'تجريش','province_id' => '8'),
            array('id' => '127','name' => 'فشم','province_id' => '8'),
            array('id' => '128','name' => 'كهريزك','province_id' => '8'),
            array('id' => '129','name' => 'پاكدشت','province_id' => '8'),
            array('id' => '130','name' => 'چهاردانگه','province_id' => '8'),
            array('id' => '131','name' => 'شريف آباد','province_id' => '8'),
            array('id' => '132','name' => 'قرچك','province_id' => '8'),
            array('id' => '133','name' => 'باقرشهر','province_id' => '8'),
            array('id' => '134','name' => 'شهريار','province_id' => '8'),
            array('id' => '135','name' => 'رباط كريم','province_id' => '8'),
            array('id' => '136','name' => 'قدس','province_id' => '8'),
            array('id' => '137','name' => 'ملارد','province_id' => '8'),
            array('id' => '138','name' => 'شهركرد','province_id' => '9'),
            array('id' => '139','name' => 'فارسان','province_id' => '9'),
            array('id' => '140','name' => 'بروجن','province_id' => '9'),
            array('id' => '141','name' => 'چلگرد','province_id' => '9'),
            array('id' => '142','name' => 'اردل','province_id' => '9'),
            array('id' => '143','name' => 'لردگان','province_id' => '9'),
            array('id' => '144','name' => 'سامان','province_id' => '9'),
            array('id' => '145','name' => 'قائن','province_id' => '10'),
            array('id' => '146','name' => 'فردوس','province_id' => '10'),
            array('id' => '147','name' => 'بيرجند','province_id' => '10'),
            array('id' => '148','name' => 'نهبندان','province_id' => '10'),
            array('id' => '149','name' => 'سربيشه','province_id' => '10'),
            array('id' => '150','name' => 'طبس مسینا','province_id' => '10'),
            array('id' => '151','name' => 'قهستان','province_id' => '10'),
            array('id' => '152','name' => 'درمیان','province_id' => '10'),
            array('id' => '153','name' => 'مشهد','province_id' => '11'),
            array('id' => '154','name' => 'نيشابور','province_id' => '11'),
            array('id' => '155','name' => 'سبزوار','province_id' => '11'),
            array('id' => '156','name' => 'كاشمر','province_id' => '11'),
            array('id' => '157','name' => 'گناباد','province_id' => '11'),
            array('id' => '158','name' => 'طبس','province_id' => '11'),
            array('id' => '159','name' => 'تربت حيدريه','province_id' => '11'),
            array('id' => '160','name' => 'خواف','province_id' => '11'),
            array('id' => '161','name' => 'تربت جام','province_id' => '11'),
            array('id' => '162','name' => 'تايباد','province_id' => '11'),
            array('id' => '163','name' => 'قوچان','province_id' => '11'),
            array('id' => '164','name' => 'سرخس','province_id' => '11'),
            array('id' => '165','name' => 'بردسكن','province_id' => '11'),
            array('id' => '166','name' => 'فريمان','province_id' => '11'),
            array('id' => '167','name' => 'چناران','province_id' => '11'),
            array('id' => '168','name' => 'درگز','province_id' => '11'),
            array('id' => '169','name' => 'كلات','province_id' => '11'),
            array('id' => '170','name' => 'طرقبه','province_id' => '11'),
            array('id' => '171','name' => 'سر ولایت','province_id' => '11'),
            array('id' => '172','name' => 'بجنورد','province_id' => '12'),
            array('id' => '173','name' => 'اسفراين','province_id' => '12'),
            array('id' => '174','name' => 'جاجرم','province_id' => '12'),
            array('id' => '175','name' => 'شيروان','province_id' => '12'),
            array('id' => '176','name' => 'آشخانه','province_id' => '12'),
            array('id' => '177','name' => 'گرمه','province_id' => '12'),
            array('id' => '178','name' => 'ساروج','province_id' => '12'),
            array('id' => '179','name' => 'اهواز','province_id' => '13'),
            array('id' => '180','name' => 'ايرانشهر','province_id' => '13'),
            array('id' => '181','name' => 'شوش','province_id' => '13'),
            array('id' => '182','name' => 'آبادان','province_id' => '13'),
            array('id' => '183','name' => 'خرمشهر','province_id' => '13'),
            array('id' => '184','name' => 'مسجد سليمان','province_id' => '13'),
            array('id' => '185','name' => 'ايذه','province_id' => '13'),
            array('id' => '186','name' => 'شوشتر','province_id' => '13'),
            array('id' => '187','name' => 'انديمشك','province_id' => '13'),
            array('id' => '188','name' => 'سوسنگرد','province_id' => '13'),
            array('id' => '189','name' => 'هويزه','province_id' => '13'),
            array('id' => '190','name' => 'دزفول','province_id' => '13'),
            array('id' => '191','name' => 'شادگان','province_id' => '13'),
            array('id' => '192','name' => 'بندر ماهشهر','province_id' => '13'),
            array('id' => '193','name' => 'بندر امام خميني','province_id' => '13'),
            array('id' => '194','name' => 'اميديه','province_id' => '13'),
            array('id' => '195','name' => 'بهبهان','province_id' => '13'),
            array('id' => '196','name' => 'رامهرمز','province_id' => '13'),
            array('id' => '197','name' => 'باغ ملك','province_id' => '13'),
            array('id' => '198','name' => 'هنديجان','province_id' => '13'),
            array('id' => '199','name' => 'لالي','province_id' => '13'),
            array('id' => '200','name' => 'رامشیر','province_id' => '13'),
            array('id' => '201','name' => 'حمیدیه','province_id' => '13'),
            array('id' => '202','name' => 'دغاغله','province_id' => '13'),
            array('id' => '203','name' => 'ملاثانی','province_id' => '13'),
            array('id' => '204','name' => 'شادگان','province_id' => '13'),
            array('id' => '205','name' => 'ویسی','province_id' => '13'),
            array('id' => '206','name' => 'زنجان','province_id' => '14'),
            array('id' => '207','name' => 'ابهر','province_id' => '14'),
            array('id' => '208','name' => 'خدابنده','province_id' => '14'),
            array('id' => '209','name' => 'كارم','province_id' => '14'),
            array('id' => '210','name' => 'ماهنشان','province_id' => '14'),
            array('id' => '211','name' => 'خرمدره','province_id' => '14'),
            array('id' => '212','name' => 'ايجرود','province_id' => '14'),
            array('id' => '213','name' => 'زرين آباد','province_id' => '14'),
            array('id' => '214','name' => 'آب بر','province_id' => '14'),
            array('id' => '215','name' => 'قيدار','province_id' => '14'),
            array('id' => '216','name' => 'سمنان','province_id' => '15'),
            array('id' => '217','name' => 'شاهرود','province_id' => '15'),
            array('id' => '218','name' => 'گرمسار','province_id' => '15'),
            array('id' => '219','name' => 'ايوانكي','province_id' => '15'),
            array('id' => '220','name' => 'دامغان','province_id' => '15'),
            array('id' => '221','name' => 'بسطام','province_id' => '15'),
            array('id' => '222','name' => 'زاهدان','province_id' => '16'),
            array('id' => '223','name' => 'چابهار','province_id' => '16'),
            array('id' => '224','name' => 'خاش','province_id' => '16'),
            array('id' => '225','name' => 'سراوان','province_id' => '16'),
            array('id' => '226','name' => 'زابل','province_id' => '16'),
            array('id' => '227','name' => 'سرباز','province_id' => '16'),
            array('id' => '228','name' => 'نيكشهر','province_id' => '16'),
            array('id' => '229','name' => 'ايرانشهر','province_id' => '16'),
            array('id' => '230','name' => 'راسك','province_id' => '16'),
            array('id' => '231','name' => 'ميرجاوه','province_id' => '16'),
            array('id' => '232','name' => 'شيراز','province_id' => '17'),
            array('id' => '233','name' => 'اقليد','province_id' => '17'),
            array('id' => '234','name' => 'داراب','province_id' => '17'),
            array('id' => '235','name' => 'فسا','province_id' => '17'),
            array('id' => '236','name' => 'مرودشت','province_id' => '17'),
            array('id' => '237','name' => 'خرم بيد','province_id' => '17'),
            array('id' => '238','name' => 'آباده','province_id' => '17'),
            array('id' => '239','name' => 'كازرون','province_id' => '17'),
            array('id' => '240','name' => 'ممسني','province_id' => '17'),
            array('id' => '241','name' => 'سپيدان','province_id' => '17'),
            array('id' => '242','name' => 'لار','province_id' => '17'),
            array('id' => '243','name' => 'فيروز آباد','province_id' => '17'),
            array('id' => '244','name' => 'جهرم','province_id' => '17'),
            array('id' => '245','name' => 'ني ريز','province_id' => '17'),
            array('id' => '246','name' => 'استهبان','province_id' => '17'),
            array('id' => '247','name' => 'لامرد','province_id' => '17'),
            array('id' => '248','name' => 'مهر','province_id' => '17'),
            array('id' => '249','name' => 'حاجي آباد','province_id' => '17'),
            array('id' => '250','name' => 'نورآباد','province_id' => '17'),
            array('id' => '251','name' => 'اردكان','province_id' => '17'),
            array('id' => '252','name' => 'صفاشهر','province_id' => '17'),
            array('id' => '253','name' => 'ارسنجان','province_id' => '17'),
            array('id' => '254','name' => 'قيروكارزين','province_id' => '17'),
            array('id' => '255','name' => 'سوريان','province_id' => '17'),
            array('id' => '256','name' => 'فراشبند','province_id' => '17'),
            array('id' => '257','name' => 'سروستان','province_id' => '17'),
            array('id' => '258','name' => 'ارژن','province_id' => '17'),
            array('id' => '259','name' => 'گويم','province_id' => '17'),
            array('id' => '260','name' => 'داريون','province_id' => '17'),
            array('id' => '261','name' => 'زرقان','province_id' => '17'),
            array('id' => '262','name' => 'خان زنیان','province_id' => '17'),
            array('id' => '263','name' => 'کوار','province_id' => '17'),
            array('id' => '264','name' => 'ده بید','province_id' => '17'),
            array('id' => '265','name' => 'باب انار/خفر','province_id' => '17'),
            array('id' => '266','name' => 'بوانات','province_id' => '17'),
            array('id' => '267','name' => 'خرامه','province_id' => '17'),
            array('id' => '268','name' => 'خنج','province_id' => '17'),
            array('id' => '269','name' => 'سیاخ دارنگون','province_id' => '17'),
            array('id' => '270','name' => 'قزوين','province_id' => '18'),
            array('id' => '271','name' => 'تاكستان','province_id' => '18'),
            array('id' => '272','name' => 'آبيك','province_id' => '18'),
            array('id' => '273','name' => 'بوئين زهرا','province_id' => '18'),
            array('id' => '274','name' => 'قم','province_id' => '19'),
            array('id' => '275','name' => 'طالقان','province_id' => '5'),
            array('id' => '276','name' => 'نظرآباد','province_id' => '5'),
            array('id' => '277','name' => 'اشتهارد','province_id' => '5'),
            array('id' => '278','name' => 'هشتگرد','province_id' => '5'),
            array('id' => '279','name' => 'كن','province_id' => '5'),
            array('id' => '280','name' => 'آسارا','province_id' => '5'),
            array('id' => '281','name' => 'شهرک گلستان','province_id' => '5'),
            array('id' => '282','name' => 'اندیشه','province_id' => '5'),
            array('id' => '283','name' => 'كرج','province_id' => '5'),
            array('id' => '284','name' => 'نظر آباد','province_id' => '5'),
            array('id' => '285','name' => 'گوهردشت','province_id' => '5'),
            array('id' => '286','name' => 'ماهدشت','province_id' => '5'),
            array('id' => '287','name' => 'مشکین دشت','province_id' => '5'),
            array('id' => '288','name' => 'سنندج','province_id' => '20'),
            array('id' => '289','name' => 'ديواندره','province_id' => '20'),
            array('id' => '290','name' => 'بانه','province_id' => '20'),
            array('id' => '291','name' => 'بيجار','province_id' => '20'),
            array('id' => '292','name' => 'سقز','province_id' => '20'),
            array('id' => '293','name' => 'كامياران','province_id' => '20'),
            array('id' => '294','name' => 'قروه','province_id' => '20'),
            array('id' => '295','name' => 'مريوان','province_id' => '20'),
            array('id' => '296','name' => 'صلوات آباد','province_id' => '20'),
            array('id' => '297','name' => 'حسن آباد','province_id' => '20'),
            array('id' => '298','name' => 'كرمان','province_id' => '21'),
            array('id' => '299','name' => 'راور','province_id' => '21'),
            array('id' => '300','name' => 'بابك','province_id' => '21'),
            array('id' => '301','name' => 'انار','province_id' => '21'),
            array('id' => '302','name' => 'کوهبنان','province_id' => '21'),
            array('id' => '303','name' => 'رفسنجان','province_id' => '21'),
            array('id' => '304','name' => 'بافت','province_id' => '21'),
            array('id' => '305','name' => 'سيرجان','province_id' => '21'),
            array('id' => '306','name' => 'كهنوج','province_id' => '21'),
            array('id' => '307','name' => 'زرند','province_id' => '21'),
            array('id' => '308','name' => 'بم','province_id' => '21'),
            array('id' => '309','name' => 'جيرفت','province_id' => '21'),
            array('id' => '310','name' => 'بردسير','province_id' => '21'),
            array('id' => '311','name' => 'كرمانشاه','province_id' => '22'),
            array('id' => '312','name' => 'اسلام آباد غرب','province_id' => '22'),
            array('id' => '313','name' => 'سر پل ذهاب','province_id' => '22'),
            array('id' => '314','name' => 'كنگاور','province_id' => '22'),
            array('id' => '315','name' => 'سنقر','province_id' => '22'),
            array('id' => '316','name' => 'قصر شيرين','province_id' => '22'),
            array('id' => '317','name' => 'گيلان غرب','province_id' => '22'),
            array('id' => '318','name' => 'هرسين','province_id' => '22'),
            array('id' => '319','name' => 'صحنه','province_id' => '22'),
            array('id' => '320','name' => 'پاوه','province_id' => '22'),
            array('id' => '321','name' => 'جوانرود','province_id' => '22'),
            array('id' => '322','name' => 'شاهو','province_id' => '22'),
            array('id' => '323','name' => 'ياسوج','province_id' => '23'),
            array('id' => '324','name' => 'گچساران','province_id' => '23'),
            array('id' => '325','name' => 'دنا','province_id' => '23'),
            array('id' => '326','name' => 'دوگنبدان','province_id' => '23'),
            array('id' => '327','name' => 'سي سخت','province_id' => '23'),
            array('id' => '328','name' => 'دهدشت','province_id' => '23'),
            array('id' => '329','name' => 'ليكك','province_id' => '23'),
            array('id' => '330','name' => 'گرگان','province_id' => '24'),
            array('id' => '331','name' => 'آق قلا','province_id' => '24'),
            array('id' => '332','name' => 'گنبد كاووس','province_id' => '24'),
            array('id' => '333','name' => 'علي آباد كتول','province_id' => '24'),
            array('id' => '334','name' => 'مينو دشت','province_id' => '24'),
            array('id' => '335','name' => 'تركمن','province_id' => '24'),
            array('id' => '336','name' => 'كردكوي','province_id' => '24'),
            array('id' => '337','name' => 'بندر گز','province_id' => '24'),
            array('id' => '338','name' => 'كلاله','province_id' => '24'),
            array('id' => '339','name' => 'آزاد شهر','province_id' => '24'),
            array('id' => '340','name' => 'راميان','province_id' => '24'),
            array('id' => '341','name' => 'رشت','province_id' => '25'),
            array('id' => '342','name' => 'منجيل','province_id' => '25'),
            array('id' => '343','name' => 'لنگرود','province_id' => '25'),
            array('id' => '344','name' => 'رود سر','province_id' => '25'),
            array('id' => '345','name' => 'تالش','province_id' => '25'),
            array('id' => '346','name' => 'آستارا','province_id' => '25'),
            array('id' => '347','name' => 'ماسوله','province_id' => '25'),
            array('id' => '348','name' => 'آستانه اشرفيه','province_id' => '25'),
            array('id' => '349','name' => 'رودبار','province_id' => '25'),
            array('id' => '350','name' => 'فومن','province_id' => '25'),
            array('id' => '351','name' => 'صومعه سرا','province_id' => '25'),
            array('id' => '352','name' => 'بندرانزلي','province_id' => '25'),
            array('id' => '353','name' => 'كلاچاي','province_id' => '25'),
            array('id' => '354','name' => 'هشتپر','province_id' => '25'),
            array('id' => '355','name' => 'رضوان شهر','province_id' => '25'),
            array('id' => '356','name' => 'ماسال','province_id' => '25'),
            array('id' => '357','name' => 'شفت','province_id' => '25'),
            array('id' => '358','name' => 'سياهكل','province_id' => '25'),
            array('id' => '359','name' => 'املش','province_id' => '25'),
            array('id' => '360','name' => 'لاهیجان','province_id' => '25'),
            array('id' => '361','name' => 'خشک بيجار','province_id' => '25'),
            array('id' => '362','name' => 'خمام','province_id' => '25'),
            array('id' => '363','name' => 'لشت نشا','province_id' => '25'),
            array('id' => '364','name' => 'بندر کياشهر','province_id' => '25'),
            array('id' => '365','name' => 'خرم آباد','province_id' => '26'),
            array('id' => '366','name' => 'ماهشهر','province_id' => '26'),
            array('id' => '367','name' => 'دزفول','province_id' => '26'),
            array('id' => '368','name' => 'بروجرد','province_id' => '26'),
            array('id' => '369','name' => 'دورود','province_id' => '26'),
            array('id' => '370','name' => 'اليگودرز','province_id' => '26'),
            array('id' => '371','name' => 'ازنا','province_id' => '26'),
            array('id' => '372','name' => 'نور آباد','province_id' => '26'),
            array('id' => '373','name' => 'كوهدشت','province_id' => '26'),
            array('id' => '374','name' => 'الشتر','province_id' => '26'),
            array('id' => '375','name' => 'پلدختر','province_id' => '26'),
            array('id' => '376','name' => 'ساري','province_id' => '27'),
            array('id' => '377','name' => 'آمل','province_id' => '27'),
            array('id' => '378','name' => 'بابل','province_id' => '27'),
            array('id' => '379','name' => 'بابلسر','province_id' => '27'),
            array('id' => '380','name' => 'بهشهر','province_id' => '27'),
            array('id' => '381','name' => 'تنكابن','province_id' => '27'),
            array('id' => '382','name' => 'جويبار','province_id' => '27'),
            array('id' => '383','name' => 'چالوس','province_id' => '27'),
            array('id' => '384','name' => 'رامسر','province_id' => '27'),
            array('id' => '385','name' => 'سواد كوه','province_id' => '27'),
            array('id' => '386','name' => 'قائم شهر','province_id' => '27'),
            array('id' => '387','name' => 'نكا','province_id' => '27'),
            array('id' => '388','name' => 'نور','province_id' => '27'),
            array('id' => '389','name' => 'بلده','province_id' => '27'),
            array('id' => '390','name' => 'نوشهر','province_id' => '27'),
            array('id' => '391','name' => 'پل سفيد','province_id' => '27'),
            array('id' => '392','name' => 'محمود آباد','province_id' => '27'),
            array('id' => '393','name' => 'فريدون كنار','province_id' => '27'),
            array('id' => '394','name' => 'اراك','province_id' => '28'),
            array('id' => '395','name' => 'آشتيان','province_id' => '28'),
            array('id' => '396','name' => 'تفرش','province_id' => '28'),
            array('id' => '397','name' => 'خمين','province_id' => '28'),
            array('id' => '398','name' => 'دليجان','province_id' => '28'),
            array('id' => '399','name' => 'ساوه','province_id' => '28'),
            array('id' => '400','name' => 'سربند','province_id' => '28'),
            array('id' => '401','name' => 'محلات','province_id' => '28'),
            array('id' => '402','name' => 'شازند','province_id' => '28'),
            array('id' => '403','name' => 'بندرعباس','province_id' => '29'),
            array('id' => '404','name' => 'قشم','province_id' => '29'),
            array('id' => '405','name' => 'كيش','province_id' => '29'),
            array('id' => '406','name' => 'بندر لنگه','province_id' => '29'),
            array('id' => '407','name' => 'بستك','province_id' => '29'),
            array('id' => '408','name' => 'حاجي آباد','province_id' => '29'),
            array('id' => '409','name' => 'دهبارز','province_id' => '29'),
            array('id' => '410','name' => 'انگهران','province_id' => '29'),
            array('id' => '411','name' => 'ميناب','province_id' => '29'),
            array('id' => '412','name' => 'ابوموسي','province_id' => '29'),
            array('id' => '413','name' => 'بندر جاسك','province_id' => '29'),
            array('id' => '414','name' => 'تنب بزرگ','province_id' => '29'),
            array('id' => '415','name' => 'بندر خمیر','province_id' => '29'),
            array('id' => '416','name' => 'پارسیان','province_id' => '29'),
            array('id' => '417','name' => 'قشم','province_id' => '29'),
            array('id' => '418','name' => 'همدان','province_id' => '30'),
            array('id' => '419','name' => 'ملاير','province_id' => '30'),
            array('id' => '420','name' => 'تويسركان','province_id' => '30'),
            array('id' => '421','name' => 'نهاوند','province_id' => '30'),
            array('id' => '422','name' => 'كبودر اهنگ','province_id' => '30'),
            array('id' => '423','name' => 'رزن','province_id' => '30'),
            array('id' => '424','name' => 'اسدآباد','province_id' => '30'),
            array('id' => '425','name' => 'بهار','province_id' => '30'),
            array('id' => '426','name' => 'يزد','province_id' => '31'),
            array('id' => '427','name' => 'تفت','province_id' => '31'),
            array('id' => '428','name' => 'اردكان','province_id' => '31'),
            array('id' => '429','name' => 'ابركوه','province_id' => '31'),
            array('id' => '430','name' => 'ميبد','province_id' => '31'),
            array('id' => '431','name' => 'طبس','province_id' => '31'),
            array('id' => '432','name' => 'بافق','province_id' => '31'),
            array('id' => '433','name' => 'مهريز','province_id' => '31'),
            array('id' => '434','name' => 'اشكذر','province_id' => '31'),
            array('id' => '435','name' => 'هرات','province_id' => '31'),
            array('id' => '436','name' => 'خضرآباد','province_id' => '31'),
            array('id' => '437','name' => 'شاهديه','province_id' => '31'),
            array('id' => '438','name' => 'حمیدیه شهر','province_id' => '31'),
            array('id' => '439','name' => 'سید میرزا','province_id' => '31'),
            array('id' => '440','name' => 'زارچ','province_id' => '31')
        );

        foreach ($locations as $location) {
            City::create($location);
        }
    }
}
